# Copyright 2024 Enterprise Accounting Team
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
"""
Budget Budget Model (BM-001)
============================

Implements ``budget.budget`` — the foundational header model for the
``account_budget_management`` addon (FEATURE-003). This module contains the
budget-level metadata: name, auto-generated reference, responsible user,
fiscal window (``date_from``/``date_to`` + optional ``period_type``), a
draft → confirmed → closed → cancelled state machine, a one-to-many
relationship to ``budget.budget.line``, and chatter / activity tracking via
``mail.thread`` / ``mail.activity.mixin`` composition.

Story Mapping
-------------
* BM-001 Scenario 1 — Create a new budget record with the required
  attributes (name, fiscal period, optional responsible person and notes).
* BM-001 Scenario 4 — ``action_confirm`` validates that the budget has at
  least one line with a positive ``planned_amount`` before transitioning
  ``draft → confirmed``; only ``account.group_account_manager`` members may
  execute ``action_reset_draft``.
* BM-001 Scenario 5 — ``copy_data`` produces a draft duplicate with the
  ``(copy)`` suffix, a blank ``reference`` (re-generated by ``create``),
  and ``copied_from_id`` populated for audit-trail continuity.
* BM-001 Scenario 6 — Each budget carries a unique per-company
  ``reference`` generated via the ``budget.budget`` ``ir.sequence``.

Rules Compliance
----------------
* R-01 — No cross-module imports. This file imports only from ``odoo``
  (core) and the Python standard library ``logging`` module.
* R-03 — ``_name = 'budget.budget'`` is a net-new model. ``_inherit`` is
  used purely to compose ``mail.thread`` and ``mail.activity.mixin`` behaviour.
* R-05 — No redefinition of fields on ``account.move`` or
  ``account.move.line``. Aggregations over posted journal entries are
  delegated to ``budget.budget.line`` (which holds the
  ``variance_actual`` computed field per BM-004).
* R-07 — No ``sudo()`` calls appear in this file.
* R-08 — No ``variance_*`` prefixed fields are declared on this model;
  those belong on ``budget.budget.line``. ``alert_*`` prefixed fields are
  confined to relational counts and boolean flags so that BM-004 and
  BM-005 remain field-partitioned.
"""

import logging

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError

_logger = logging.getLogger(__name__)


class BudgetBudget(models.Model):
    """Header record for a budget.

    A ``budget.budget`` record owns one or more ``budget.budget.line``
    children (line items linking GL accounts and analytic distributions to
    planned amounts) and one or more ``budget.alert`` children (threshold
    events produced by the BM-005 alert cron). The header manages the
    budget lifecycle (``draft → confirmed → closed``, with an orthogonal
    ``cancelled`` terminal state) and exposes aggregate metrics
    (``total_planned``, ``total_actual``, ``total_variance``,
    ``consumption_percent``) for the UI and for dashboard kanbans.

    The model composes :class:`mail.thread` and :class:`mail.activity.mixin`
    so that every state transition posts a note to the chatter, enabling
    an auditable lifecycle trail. ``_check_company_auto = True`` ensures
    that related ``Many2one`` fields bearing ``check_company=True`` are
    automatically validated against the record's ``company_id`` by the
    ORM.
    """

    _name = 'budget.budget'
    _description = 'Budget'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'date_from desc, reference'
    _check_company_auto = True

    # ------------------------------------------------------------------
    # Section 3.1 — Identification
    # ------------------------------------------------------------------
    name = fields.Char(
        string='Name',
        required=True,
        translate=True,
        tracking=True,
    )
    reference = fields.Char(
        string='Reference',
        required=True,
        readonly=True,
        copy=False,
        default=lambda self: _('New'),
        tracking=True,
        help="Auto-generated via the 'budget.budget' ir.sequence on "
             "create. Unique per company.",
    )
    description = fields.Text(
        string='Notes',
        translate=True,
    )
    active = fields.Boolean(string='Active', default=True)

    # ------------------------------------------------------------------
    # Section 3.2 — Ownership
    # ------------------------------------------------------------------
    user_id = fields.Many2one(
        comodel_name='res.users',
        string='Responsible User',
        default=lambda self: self.env.user,
        required=True,
        tracking=True,
    )
    company_id = fields.Many2one(
        comodel_name='res.company',
        string='Company',
        required=True,
        default=lambda self: self.env.company,
        index=True,
    )
    currency_id = fields.Many2one(
        comodel_name='res.currency',
        related='company_id.currency_id',
        store=True,
        string='Currency',
    )

    # ------------------------------------------------------------------
    # Section 3.3 — Fiscal window
    # ------------------------------------------------------------------
    date_from = fields.Date(
        string='Start Date',
        required=True,
        tracking=True,
    )
    date_to = fields.Date(
        string='End Date',
        required=True,
        tracking=True,
    )
    period_type = fields.Selection(
        selection=[
            ('monthly', 'Monthly'),
            ('quarterly', 'Quarterly'),
            ('annual', 'Annual'),
            ('custom', 'Custom'),
        ],
        string='Period Type',
        default='annual',
        required=True,
        tracking=True,
        help="Default period granularity for period-allocation operations "
             "on this budget's lines.",
    )

    # ------------------------------------------------------------------
    # Section 3.4 — State machine
    # ------------------------------------------------------------------
    state = fields.Selection(
        selection=[
            ('draft', 'Draft'),
            ('confirmed', 'Confirmed'),
            ('closed', 'Closed'),
            ('cancelled', 'Cancelled'),
        ],
        string='Status',
        default='draft',
        required=True,
        readonly=True,
        copy=False,
        tracking=True,
        index=True,
    )

    # ------------------------------------------------------------------
    # Section 3.5 — Lines + aggregates
    # ------------------------------------------------------------------
    line_ids = fields.One2many(
        comodel_name='budget.budget.line',
        inverse_name='budget_id',
        string='Budget Lines',
        copy=True,
    )
    line_count = fields.Integer(
        string='Line Count',
        compute='_compute_line_count',
    )
    total_planned = fields.Monetary(
        string='Total Planned',
        compute='_compute_totals',
        store=True,
        currency_field='currency_id',
        tracking=True,
    )
    total_actual = fields.Monetary(
        string='Total Actual',
        compute='_compute_totals',
        currency_field='currency_id',
        help="Aggregated actuals across all budget lines; computed from "
             "line.variance_actual.",
    )
    total_variance = fields.Monetary(
        string='Total Variance',
        compute='_compute_totals',
        currency_field='currency_id',
    )
    consumption_percent = fields.Float(
        string='Overall Consumption (%)',
        compute='_compute_totals',
        digits=(5, 2),
    )

    # ------------------------------------------------------------------
    # Section 3.6 — Alert summary (R-08: alert_ prefix only, no variance_)
    # ------------------------------------------------------------------
    alert_ids = fields.One2many(
        comodel_name='budget.alert',
        inverse_name='budget_id',
        string='Alert History',
        readonly=True,
    )
    alert_count = fields.Integer(
        string='Alert Count',
        compute='_compute_alert_count',
    )
    alert_active = fields.Boolean(
        string='Has Active Alerts',
        compute='_compute_alert_count',
        help="True when at least one alert event exists for any line of "
             "this budget.",
    )

    # ------------------------------------------------------------------
    # Section 3.7 — Source lineage (for copy_data override)
    # ------------------------------------------------------------------
    copied_from_id = fields.Many2one(
        comodel_name='budget.budget',
        string='Copied From',
        readonly=True,
        copy=False,
        ondelete='set null',
        help="Points to the source budget record when this budget was "
             "duplicated via the copy action.",
    )

    # ==================================================================
    # Phase 4 — Compute methods
    # ==================================================================

    @api.depends('line_ids')
    def _compute_line_count(self):
        """Count the number of budget lines per header."""
        for budget in self:
            budget.line_count = len(budget.line_ids)

    @api.depends(
        'line_ids',
        'line_ids.planned_amount',
        'line_ids.variance_actual',
    )
    def _compute_totals(self):
        """Aggregate planned / actual / variance / consumption per budget.

        ``total_planned`` is stored so that search / group-by operations on
        the budget list can leverage the indexed column without triggering
        a recompute. ``total_actual``, ``total_variance``, and
        ``consumption_percent`` are computed non-stored because they depend
        on the child line's ``variance_actual`` field, which itself
        aggregates posted ``account.move.line`` rows and is therefore
        invalidated whenever journal entries change.

        Reads the ``variance_actual`` computed field on each
        ``budget.budget.line`` child. That field (declared on
        ``budget.budget.line`` in BM-004 per R-08) performs a single
        ``read_group`` over posted ``account.move.line`` rows, so the
        aggregation here is O(n) in the number of lines rather than O(n*m)
        in lines-times-moves.
        """
        for budget in self:
            if not budget.line_ids:
                budget.total_planned = 0.0
                budget.total_actual = 0.0
                budget.total_variance = 0.0
                budget.consumption_percent = 0.0
                continue
            planned = sum(budget.line_ids.mapped('planned_amount'))
            actual = sum(budget.line_ids.mapped('variance_actual'))
            budget.total_planned = planned
            budget.total_actual = actual
            budget.total_variance = actual - planned
            budget.consumption_percent = (
                (actual / planned * 100.0) if planned else 0.0
            )

    @api.depends('alert_ids')
    def _compute_alert_count(self):
        """Count alert events and flag presence of any alert."""
        for budget in self:
            budget.alert_count = len(budget.alert_ids)
            budget.alert_active = bool(budget.alert_ids)

    # ==================================================================
    # Phase 5 — Constraints
    # ==================================================================

    @api.constrains('date_from', 'date_to')
    def _check_dates(self):
        """Ensure the fiscal window is valid (start ≤ end)."""
        for budget in self:
            if budget.date_from and budget.date_to and (
                budget.date_from > budget.date_to
            ):
                raise ValidationError(_(
                    "Budget start date (%(f)s) must be on or before the "
                    "end date (%(t)s).",
                    f=budget.date_from,
                    t=budget.date_to,
                ))

    _sql_constraints = [
        (
            'unique_reference_per_company',
            'UNIQUE(reference, company_id)',
            'Budget reference must be unique per company.',
        ),
    ]

    # ==================================================================
    # Phase 6 — Sequence hook on create
    # ==================================================================

    @api.model_create_multi
    def create(self, vals_list):
        """Generate the company-scoped ``reference`` via ``ir.sequence``.

        Mirrors the precedent set by ``account.payment._compute_name``
        (``addons/account/models/account_payment.py``) which looks up the
        sequence via ``self.env['ir.sequence'].with_company(company_id)``
        so that the sequence increments per company rather than globally.
        The ``budget.budget`` sequence itself is declared in
        ``data/budget_data.xml``. If the sequence is not yet present at
        create-time (e.g. during module install before data files load),
        the fallback value ``_('New')`` is preserved so that the record is
        still creatable and can be re-sequenced later via a manual update.
        """
        for vals in vals_list:
            if not vals.get('reference') or vals.get('reference') == _('New'):
                company_id = vals.get('company_id') or self.env.company.id
                seq = self.env['ir.sequence'].with_company(
                    company_id,
                ).next_by_code('budget.budget')
                if seq:
                    vals['reference'] = seq
                else:
                    _logger.warning(
                        "No ir.sequence with code 'budget.budget' found for "
                        "company_id=%s — falling back to default reference.",
                        company_id,
                    )
                    vals['reference'] = _('New')
        return super().create(vals_list)

    # ==================================================================
    # Phase 7 — State transition methods
    # ==================================================================

    def action_confirm(self):
        """Transition draft → confirmed.

        Enforces BM-001 Scenario 4 validation:

        * The budget must currently be in the ``draft`` state.
        * It must contain at least one ``budget.budget.line`` child.
        * At least one line must carry a positive ``planned_amount`` so
          that the budget represents a non-trivial financial target.

        On success, the state is updated and a note is posted to the
        chatter for audit-trail continuity.
        """
        for budget in self:
            if budget.state != 'draft':
                raise UserError(_(
                    "Only draft budgets can be confirmed (current state: "
                    "%(state)s).",
                    state=budget.state,
                ))
            if not budget.line_ids:
                raise UserError(_(
                    "Cannot confirm budget '%(name)s' — no budget lines.",
                    name=budget.name,
                ))
            if not any(line.planned_amount > 0 for line in budget.line_ids):
                raise UserError(_(
                    "Cannot confirm budget '%(name)s' — at least one line "
                    "must have a positive planned amount.",
                    name=budget.name,
                ))
            budget.state = 'confirmed'
            budget.message_post(
                body=_(
                    "Budget confirmed by %(user)s.",
                    user=self.env.user.name,
                ),
                subtype_xmlid='mail.mt_note',
            )
            _logger.info(
                "Budget %s (id=%s) confirmed by user %s (id=%s).",
                budget.reference,
                budget.id,
                self.env.user.name,
                self.env.user.id,
            )
        return True

    def action_close(self):
        """Transition confirmed → closed.

        A closed budget is terminal: no further state transitions are
        permitted except for a manager-only reset via
        :meth:`action_reset_draft`. Only ``confirmed`` budgets may be
        closed.
        """
        for budget in self:
            if budget.state != 'confirmed':
                raise UserError(_(
                    "Only confirmed budgets can be closed (current state: "
                    "%(state)s).",
                    state=budget.state,
                ))
            budget.state = 'closed'
            budget.message_post(
                body=_(
                    "Budget closed by %(user)s.",
                    user=self.env.user.name,
                ),
                subtype_xmlid='mail.mt_note',
            )
            _logger.info(
                "Budget %s (id=%s) closed by user %s (id=%s).",
                budget.reference,
                budget.id,
                self.env.user.name,
                self.env.user.id,
            )
        return True

    def action_reset_draft(self):
        """Reset any non-draft budget back to the draft state.

        Restricted to members of ``account.group_account_manager`` to
        prevent accidental rollback of confirmed or closed budgets by
        regular accounting users. Budgets already in ``draft`` are left
        unchanged (no-op for idempotency) so that batch calls across
        mixed-state recordsets do not raise spurious errors.
        """
        if not self.env.user.has_group('account.group_account_manager'):
            raise UserError(_(
                "Only accounting managers can reset a budget to draft.",
            ))
        for budget in self:
            if budget.state == 'draft':
                continue
            budget.state = 'draft'
            budget.message_post(
                body=_(
                    "Budget reset to draft by %(user)s.",
                    user=self.env.user.name,
                ),
                subtype_xmlid='mail.mt_note',
            )
            _logger.info(
                "Budget %s (id=%s) reset to draft by user %s (id=%s).",
                budget.reference,
                budget.id,
                self.env.user.name,
                self.env.user.id,
            )
        return True

    def action_cancel(self):
        """Cancel any budget not already closed.

        Cancellation is an orthogonal terminal state distinct from
        ``closed`` — a closed budget has completed its fiscal lifecycle
        whereas a cancelled budget was abandoned before completion. For
        this reason, closed budgets cannot be cancelled; a manager must
        first reset them to draft if cancellation is required.
        """
        for budget in self:
            if budget.state in ('closed',):
                raise UserError(_(
                    "Closed budgets cannot be cancelled.",
                ))
            budget.state = 'cancelled'
            budget.message_post(
                body=_(
                    "Budget cancelled by %(user)s.",
                    user=self.env.user.name,
                ),
                subtype_xmlid='mail.mt_note',
            )
            _logger.info(
                "Budget %s (id=%s) cancelled by user %s (id=%s).",
                budget.reference,
                budget.id,
                self.env.user.name,
                self.env.user.id,
            )
        return True

    # ==================================================================
    # Phase 8 — Copy override (BM-001 Scenario 5 — Duplication)
    # ==================================================================

    def copy_data(self, default=None):
        """Duplicate the budget into a fresh draft record.

        Implements BM-001 Scenario 5 by:

        * Appending ``(copy)`` to the name unless the caller supplied an
          explicit name via ``default``.
        * Resetting the ``reference`` placeholder so that ``create`` will
          generate a fresh sequence number for the duplicate.
        * Forcing the duplicate back to ``draft`` regardless of the source
          state so that the duplicate can be re-configured before
          activation.
        * Linking ``copied_from_id`` to the source record for audit-trail
          continuity, enabling "where did this budget come from?" queries
          on the duplicate.

        The one-to-many ``line_ids`` is copied automatically because the
        field is declared with ``copy=True``; likewise individual lines
        carry any analytic distributions defined on them. This mirrors
        the Odoo-19 override idiom observed in
        ``addons/analytic/models/analytic_account.py`` line 114.
        """
        default = dict(default or {})
        vals_list = super().copy_data(default=default)
        for budget, vals in zip(self, vals_list):
            if 'name' not in default:
                vals['name'] = _("%(name)s (copy)", name=budget.name)
            vals['reference'] = _('New')
            vals['state'] = 'draft'
            vals['copied_from_id'] = budget.id
        return vals_list

    # ==================================================================
    # Phase 9 — Action helpers (UI smart buttons)
    # ==================================================================

    def action_open_lines(self):
        """Open the lines belonging to this budget in a list/form view.

        Pre-populates the action context with ``default_budget_id`` and
        ``default_company_id`` so that creating a new line from this
        action automatically associates it with the current budget and
        company, preserving the ``_check_company_auto`` invariant.
        """
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Budget Lines'),
            'res_model': 'budget.budget.line',
            'view_mode': 'list,form',
            'domain': [('budget_id', '=', self.id)],
            'context': {
                'default_budget_id': self.id,
                'default_company_id': self.company_id.id,
            },
        }

    def action_open_alerts(self):
        """Open the alert history for this budget in a list/form view."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Budget Alerts'),
            'res_model': 'budget.alert',
            'view_mode': 'list,form',
            'domain': [('budget_id', '=', self.id)],
        }
