# Copyright 2024 Enterprise Accounting Team
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

"""Asset Depreciation Schedule Line (FEATURE-004, AM-003 / AM-004).

Represents one period in an asset's depreciation schedule. Generated by
``account.asset._compute_depreciation_schedule`` at asset confirmation,
and posted by ``account.asset._cron_post_depreciation_entries`` (AM-004).

The model acts as both the *plan* (prior to posting) and the *audit*
(after posting) for per-period depreciation events. Each record records:

    * The scheduled date the depreciation should be posted
    * The monetary amount to depreciate for that period
    * A running cumulative depreciation total (sum of all amounts
      through this line within the asset's schedule)
    * The corresponding net book value (NBV = acquisition_cost
      - cumulative_depreciation)
    * The line's posting status (``draft``, ``posted``, ``skipped``)
    * A link to the posted ``account.move`` journal entry
      (``NULL`` while the line is draft or skipped)

Supports the Depreciation Board (AM-003) via:

    * Stored ``cumulative_depreciation`` and ``net_book_value`` fields
      for O(1) lookup during tree / kanban / graph rendering
    * Indexed ``asset_id`` FK for efficient per-asset filtering
    * Line ``state`` (draft / posted / skipped) for visual distinction

Supports the Automatic Depreciation Entries cron (AM-004) via:

    * The ``action_post()`` method, which creates a balanced
      ``account.move`` (debit depreciation expense, credit accumulated
      depreciation) and transitions the line to ``state='posted'``
    * Idempotency -- calling ``action_post()`` on an already-posted or
      skipped line is a no-op, so repeated cron runs do not create
      duplicate journal entries (AM-004 AC6)
    * Fault tolerance -- the cron caller wraps each line's
      ``action_post`` call in try/except, so one line's failure cannot
      block the rest of the batch (AM-004 AC2 / AC6)

Performance target (per AAP): < 2s full-schedule render for 480 periods
(40 years x 12 monthly entries).

AAP Rule Compliance
-------------------
* R-01 (Module independence) -- No imports from sibling CE modules
  (``account_budget_management``, ``account_deferred_revenue``,
  ``account_payment_followup``). Only ``odoo`` and the Python standard
  library ``logging`` are imported.
* R-03 (``_name`` / ``_inherit`` correctness) -- This is a net-new model
  declared via ``_name = 'account.asset.depreciation.line'``. No
  ``_inherit`` on any core model is used because the schedule line is a
  brand-new concept that does not extend any pre-existing model.
* R-05 (No core field redefinition) -- Not applicable: this file
  creates a brand-new model; it does not modify ``account.move`` or
  ``account.move.line`` field definitions.
* R-06 (Scheduled jobs via XML ``ir.cron``) -- Not applicable here; the
  cron itself lives in ``data/depreciation_cron.xml`` and invokes the
  ``account.asset._cron_post_depreciation_entries`` batch entry point.
* R-07 (No unjustified ``sudo``) -- No ``.sudo()`` calls appear in this
  file. The AM-004 cron invokes ``action_post`` through the
  ``account.asset`` batch method, which already runs with the cron
  user's accounting privileges granted by ``ir.model.access.csv``.
"""

import logging

from odoo import Command, _, api, fields, models
from odoo.exceptions import UserError, ValidationError

_logger = logging.getLogger(__name__)


class AccountAssetDepreciationLine(models.Model):
    """One period in an asset's depreciation schedule.

    Each record pairs a scheduled ``depreciation_date`` with the
    monetary ``depreciation_amount`` to be posted on that date, plus
    running-total bookkeeping fields (``cumulative_depreciation``,
    ``net_book_value``) that power the AM-003 Depreciation Board.

    Lifecycle (state machine)::

        draft ---- action_post() ----> posted
          |
          +------ action_skip() ----> skipped

    Once in ``posted`` or ``skipped`` state, ``action_post`` is a no-op
    and ``action_skip`` raises ``UserError``. This guarantees AM-004
    idempotency: the cron may safely re-run without creating duplicate
    journal entries.
    """

    _name = 'account.asset.depreciation.line'
    _description = 'Asset Depreciation Schedule Line'
    _order = 'asset_id, sequence, depreciation_date'
    _check_company_auto = True

    # ------------------------------------------------------------------
    # Relational fields
    # ------------------------------------------------------------------

    asset_id = fields.Many2one(
        comodel_name='account.asset',
        string='Asset',
        required=True,
        ondelete='cascade',
        index=True,
        help='The asset this depreciation line belongs to. Deleting a '
             'draft asset cascades to all of its schedule lines so that '
             'no orphan records remain.',
    )
    move_id = fields.Many2one(
        comodel_name='account.move',
        string='Journal Entry',
        readonly=True,
        copy=False,
        ondelete='set null',
        help='The posted journal entry created by the AM-004 '
             'depreciation cron for this line. NULL for draft or '
             'skipped lines. On journal entry deletion, the link is '
             'cleared but the schedule line persists as audit history.',
    )

    # ------------------------------------------------------------------
    # Core period / amount fields
    # ------------------------------------------------------------------

    sequence = fields.Integer(
        string='Sequence',
        default=1,
        help='Line sequence within the asset schedule (1, 2, 3, ...). '
             'Combined with ``depreciation_date`` to form the primary '
             '``_order`` clause so the schedule renders deterministically '
             'top-to-bottom in the AM-003 Depreciation Board.',
    )
    depreciation_date = fields.Date(
        string='Depreciation Date',
        required=True,
        help='The scheduled date this depreciation should be posted on. '
             'The AM-004 cron selects lines whose ``depreciation_date`` '
             'is on or before the cron execution date for posting.',
    )
    depreciation_amount = fields.Monetary(
        string='Depreciation Amount',
        required=True,
        currency_field='currency_id',
        help='Amount to debit the depreciation expense account and '
             'credit the accumulated depreciation account for this '
             'period. Must be non-negative; enforced via SQL CHECK '
             'constraint.',
    )

    # ------------------------------------------------------------------
    # Computed, stored aggregates (O(1) board rendering)
    # ------------------------------------------------------------------

    cumulative_depreciation = fields.Monetary(
        string='Cumulative Depreciation',
        currency_field='currency_id',
        compute='_compute_cumulative_and_nbv',
        store=True,
        readonly=True,
        help='Running total of all depreciation amounts for this asset '
             'up to and including this line. Stored so the AM-003 board '
             'can render 480 periods in under 2 seconds without '
             'recomputing siblings on every read.',
    )
    net_book_value = fields.Monetary(
        string='Net Book Value',
        currency_field='currency_id',
        compute='_compute_cumulative_and_nbv',
        store=True,
        readonly=True,
        help='Asset net book value at the end of this period: '
             'acquisition_cost - cumulative_depreciation. Reaches '
             'salvage_value on the final period of a fully-depreciated '
             'schedule.',
    )

    # ------------------------------------------------------------------
    # State and audit
    # ------------------------------------------------------------------

    # NOTE: ``tracking=True`` is intentionally NOT set on this Selection
    # field even though the AAP design discusses it. The depreciation line
    # model does not inherit ``mail.thread`` (chatter would add per-line
    # audit storage that scales linearly with schedule length, which can
    # be 480+ records per asset). Audit trail for asset-level state
    # transitions (draft -> open -> close) is captured on the parent
    # ``account.asset`` model, which DOES inherit ``mail.thread`` and
    # ``mail.activity.mixin`` and emits chatter messages whenever a
    # depreciation line is posted (see ``account.asset.message_post``
    # calls in ``_cron_post_depreciation_entries``).
    state = fields.Selection(
        selection=[
            ('draft', 'Draft'),
            ('posted', 'Posted'),
            ('skipped', 'Skipped'),
        ],
        string='Status',
        default='draft',
        required=True,
        copy=False,
        help='Draft: scheduled but not yet posted. '
             'Posted: journal entry created and posted. '
             'Skipped: line marked as intentionally not posted (admin '
             'only).',
    )

    # ------------------------------------------------------------------
    # Multi-company / currency (stored related for efficient ir.rule)
    # ------------------------------------------------------------------

    company_id = fields.Many2one(
        comodel_name='res.company',
        string='Company',
        related='asset_id.company_id',
        store=True,
        readonly=True,
        index=True,
        help='Company owning the parent asset. Stored so multi-company '
             '``ir.rule`` filters execute as an indexed equality check.',
    )
    currency_id = fields.Many2one(
        comodel_name='res.currency',
        string='Currency',
        related='asset_id.currency_id',
        store=True,
        readonly=True,
        help='Currency of the parent asset. Required for the Monetary '
             'field descriptors on this model.',
    )

    # ------------------------------------------------------------------
    # SQL constraints
    # ------------------------------------------------------------------

    # Odoo 19 native constraint enforcement. The ``models.Constraint`` is
    # the supported Odoo 19 mechanism that actually creates the PostgreSQL
    # CHECK constraint (see ``odoo/orm/table_objects.py::Constraint``).
    # The generated database object is named
    # ``account_asset_depreciation_line_positive_amount``.
    _positive_amount = models.Constraint(
        'CHECK(depreciation_amount >= 0)',
        'Depreciation amount must be non-negative.',
    )

    # NOTE: The legacy ``_sql_constraints`` attribute has been removed in
    # favor of the Odoo 19 canonical ``models.Constraint`` declaration
    # above (``_positive_amount``). Keeping both produced a deprecation
    # warning at module load time; the canonical ``Constraint`` already
    # creates the same PostgreSQL CHECK so removing the legacy attribute
    # is safe and eliminates the warning. See
    # addons/account_asset_management code review feedback (Checkpoint
    # 8) for the rationale.

    # ------------------------------------------------------------------
    # Computed methods
    # ------------------------------------------------------------------

    @api.depends(
        'asset_id',
        'asset_id.acquisition_cost',
        'asset_id.depreciation_line_ids',
        'asset_id.depreciation_line_ids.depreciation_amount',
        'asset_id.depreciation_line_ids.sequence',
        'sequence',
        'depreciation_amount',
    )
    def _compute_cumulative_and_nbv(self):
        """Compute the running cumulative depreciation and the NBV.

        For each line in ``self``, walk its sibling lines on the parent
        asset in the canonical schedule order (``sequence`` ascending,
        with ``depreciation_date`` as the tie-breaker) and accumulate
        the running total of ``depreciation_amount``. The cumulative
        value at the point the current line is reached becomes its
        ``cumulative_depreciation``; ``net_book_value`` follows as
        ``asset.acquisition_cost - cumulative_depreciation``.

        The method is ``store=True`` so that reads of the Depreciation
        Board are O(1) per line (no recomputation on every render).

        Edge cases handled:

            * Line with no asset (during form onchange before save):
              both fields are zeroed.
            * Line not yet present in its asset's ``depreciation_line_ids``
              recordset (transient state during create / cache
              invalidation): fall back to treating the line as the sole
              contributor so the stored value is consistent once the
              create completes and the sibling set is refreshed.
        """
        for line in self:
            asset = line.asset_id
            if not asset:
                line.cumulative_depreciation = 0.0
                line.net_book_value = 0.0
                continue

            # Sort siblings deterministically: by ``sequence``, then by
            # ``depreciation_date``. ``fields.Date.today()`` is used as
            # a stable sentinel for None dates to keep ``sorted`` total.
            today = fields.Date.today()
            siblings = asset.depreciation_line_ids.sorted(
                key=lambda sibling: (
                    sibling.sequence,
                    sibling.depreciation_date or today,
                ),
            )

            cumulative = 0.0
            found = False
            for sibling in siblings:
                cumulative += sibling.depreciation_amount or 0.0
                # Match either on persisted id (posted records) or on
                # record identity (in-memory NewIds during create).
                if sibling.id == line.id or (not sibling.id and sibling == line):
                    line.cumulative_depreciation = cumulative
                    line.net_book_value = (asset.acquisition_cost or 0.0) - cumulative
                    found = True
                    break

            if not found:
                # Edge case: line not found in its own asset's sibling
                # set (may occur briefly during concurrent writes or
                # cache-invalidation gaps). Fall back to a self-only
                # calculation so the stored value is coherent until the
                # next recompute trigger fires.
                _logger.warning(
                    "Depreciation line id=%s not found in asset %s "
                    "sibling set during recompute; falling back to "
                    "self-only cumulative/NBV calculation. The next "
                    "recompute trigger should restore the correct "
                    "running total.",
                    line.id,
                    asset.display_name,
                )
                line.cumulative_depreciation = line.depreciation_amount or 0.0
                line.net_book_value = (
                    (asset.acquisition_cost or 0.0) - line.cumulative_depreciation
                )

    # ------------------------------------------------------------------
    # Python constraints
    # ------------------------------------------------------------------

    @api.constrains('depreciation_date', 'asset_id')
    def _check_depreciation_date_within_asset_schedule(self):
        """Validate that ``depreciation_date`` >= asset start date.

        When the parent asset declares a ``depreciation_start_date``,
        every schedule line must be on or after that date. Dates before
        the start date would violate the asset-lifecycle semantics
        (depreciation cannot begin before the asset's service date) and
        would produce journal entries in periods that pre-date the
        asset's existence on the books.
        """
        for line in self:
            asset = line.asset_id
            if not asset:
                continue
            # ``depreciation_start_date`` is defined on ``account.asset``
            # (AM-002). Defensive ``getattr`` lets this constraint
            # remain inert during any transient pre-install state where
            # the parent field is not yet present on the model.
            start = getattr(asset, 'depreciation_start_date', False)
            if start and line.depreciation_date and line.depreciation_date < start:
                raise ValidationError(_(
                    "Depreciation date (%(date)s) cannot precede the "
                    "asset's depreciation start date (%(start)s) for "
                    "asset %(name)s.",
                    date=line.depreciation_date,
                    start=start,
                    name=asset.name or '',
                ))

    # ------------------------------------------------------------------
    # Action methods
    # ------------------------------------------------------------------

    def action_post(self):
        """Create and optionally post a journal entry for each draft line.

        For every line in ``self`` whose ``state == 'draft'``:

            1. Validate the parent asset has the required postings
               configuration (depreciation journal, expense account,
               accumulated-depreciation account).
            2. Build a balanced ``account.move`` with two lines:
               - Debit:  ``expense_account_id``  = depreciation amount
               - Credit: ``accumulated_depreciation_account_id`` = amount
            3. Call ``account.move.create()`` to persist the entry.
            4. If the asset's category has ``auto_post_depreciation``
               enabled, call ``move.action_post()`` to immediately
               post the entry; otherwise leave it in ``draft`` for
               accountant review.
            5. Update the schedule line: ``state='posted'`` and
               ``move_id`` set to the newly-created move.

        Idempotency (AM-004 AC6): Lines already in ``posted`` or
        ``skipped`` state are silently skipped -- re-running the cron
        is safe and will never create duplicate journal entries.

        Fault tolerance (AM-004 AC2 / AC6): Validation failures raise
        ``UserError`` so the cron's per-line try/except handler can log
        the failure and continue with the remaining lines in the batch
        without aborting the entire run.

        :return: ``True`` on successful execution.
        :raises UserError: when a draft line cannot be posted due to
            missing asset configuration (no asset, no journal, no
            expense account, no accumulated-depreciation account).
        """
        for line in self:
            if line.state != 'draft':
                # Already posted or skipped: idempotent no-op.
                _logger.info(
                    "Depreciation line id=%s skipped by action_post: "
                    "state=%s (expected 'draft').",
                    line.id, line.state,
                )
                continue

            asset = line.asset_id
            if not asset:
                raise UserError(_(
                    "Cannot post depreciation line without an asset.",
                ))
            if not asset.journal_id:
                raise UserError(_(
                    "Cannot post depreciation for asset %s: no "
                    "depreciation journal is configured.",
                    asset.name or '',
                ))
            if not asset.expense_account_id:
                raise UserError(_(
                    "Cannot post depreciation for asset %s: no expense "
                    "account is configured.",
                    asset.name or '',
                ))
            if not asset.accumulated_depreciation_account_id:
                raise UserError(_(
                    "Cannot post depreciation for asset %s: no "
                    "accumulated depreciation account is configured.",
                    asset.name or '',
                ))

            # Build the balanced journal entry (AM-004 AC1).
            move_vals = {
                'move_type': 'entry',
                'date': line.depreciation_date,
                'journal_id': asset.journal_id.id,
                'company_id': asset.company_id.id,
                'ref': _(
                    "Depreciation %(ref)s period %(seq)s",
                    ref=asset.reference or asset.name or '',
                    seq=line.sequence,
                ),
                'asset_id': asset.id,
                'asset_entry_type': 'depreciation',
                'line_ids': [
                    Command.create({
                        'account_id': asset.expense_account_id.id,
                        'name': _(
                            'Depreciation of %s', asset.name or '',
                        ),
                        'debit': line.depreciation_amount,
                        'credit': 0.0,
                        'asset_depreciation_line_id': line.id,
                    }),
                    Command.create({
                        'account_id': asset.accumulated_depreciation_account_id.id,
                        'name': _(
                            'Accumulated depreciation of %s',
                            asset.name or '',
                        ),
                        'debit': 0.0,
                        'credit': line.depreciation_amount,
                        'asset_depreciation_line_id': line.id,
                    }),
                ],
            }
            move = self.env['account.move'].create(move_vals)

            # Auto-post if the category opts in (AM-004 AC3).
            auto_post = False
            if asset.category_id:
                auto_post = bool(
                    getattr(asset.category_id, 'auto_post_depreciation', False),
                )
            if auto_post:
                move.action_post()

            line.write({'state': 'posted', 'move_id': move.id})
            _logger.info(
                "Posted depreciation line id=%s for asset %s (move id=%s, "
                "amount=%s, auto_post=%s).",
                line.id,
                asset.display_name,
                move.id,
                line.depreciation_amount,
                auto_post,
            )

        return True

    def action_skip(self):
        """Mark a single draft line as skipped.

        Admin-only transition used when an accountant chooses to
        manually handle a specific period (e.g. a one-off manual
        journal entry adjustment) and wants to exclude the scheduled
        line from the cron's automatic posting pipeline.

        :return: ``True`` on success.
        :raises UserError: when invoked on a line that is not in
            ``draft`` state. Posted entries must be reversed through
            the normal journal workflow before their schedule line can
            be retried.
        """
        self.ensure_one()
        if self.state != 'draft':
            raise UserError(_('Only draft lines can be skipped.'))
        self.write({'state': 'skipped'})
        _logger.info(
            "Depreciation line id=%s for asset %s marked as skipped.",
            self.id,
            self.asset_id.display_name if self.asset_id else '',
        )
        return True
