# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
"""Cross-language FNV-1a 32-bit parity test for the auth_v2 addon.

This test is the canonical Rule RF4 verification gate. It loads a
deterministic 100-vector JSON fixture generated by the TypeScript
canonical implementation at::

    packages/admin-ui/src/flags/__tests__/fixtures/fnv-vectors.json

and asserts that the Python ``fnv1a32(flag_name, subject)`` function in
``odoo.addons.auth_v2.models.fnv_hash`` produces byte-identical 32-bit
unsigned integer output for every vector.

The fixture is the cross-language ground truth: it is generated by the
TypeScript implementation in ``packages/admin-ui/src/flags/__tests__/
fnv-hash.spec.ts`` and loaded by both languages' test suites to assert
deterministic byte-equality.

Per Rule RF4, byte-equal output for ALL 100 vectors is required; there
are no tolerances, no skipped tests, no conditional skips by platform.

This test is purely computational -- it does NOT exercise the V2 sidecar
code paths, the flags API, the HTTP client, or any environment-variable
reads. The HTTP integration in ``auth_v2.py`` and ``feature_flags.py``
is out of scope for THIS test (covered by separate integration tests
in another agent's scope).

Five test methods are exposed:

    1. ``test_fixture_field_shape_and_ranges`` -- defensive pre-check that
       every fixture vector has the expected fields, types, and ranges so
       a corrupt fixture surfaces a clear diagnostic before the parity
       tests run with cryptic mismatch messages.

    2. ``test_fnv1a32_byte_parity`` -- THE Rule RF4 verification gate.
       For each of the 100 vectors, asserts ``fnv1a32(flag_name, subject)``
       returns the byte-identical 32-bit unsigned integer recorded in the
       fixture's ``expected_hash`` field.

    3. ``test_rollout_evaluation_parity`` -- asserts that the rollout
       decision ``(fnv1a32(flag_name, subject) % 100) < rollout_percentage``
       matches the fixture's ``expected_enabled`` boolean for every vector.
       Verifies the full 4-step evaluation produces byte-identical
       booleans across both languages.

    4. ``test_fnv1a32_default_subject_argument`` -- asserts that
       ``fnv1a32(name)`` and ``fnv1a32(name, '')`` produce identical
       output. This guards the most common Odoo call site
       (``feature_flags.is_enabled('AUTH_V2_ENABLED')``) against
       regression where the default argument is changed to ``None`` or
       similar non-string sentinel.

    5. ``test_fnv1a32_returns_uint32_range`` -- defensive test against
       sign-extension / overflow bugs. Asserts the function always
       returns an integer in ``[0, 0xFFFFFFFF]`` for both fixture inputs
       and ad-hoc edge cases (long inputs, control bytes, multi-byte
       UTF-8 characters).

See:
    - AAP Section 0.5.1.5 (Group 5 -- Odoo Addon)
    - AAP Section 0.7.2 RF4 (Flag determinism)
    - AAP Section 0.7.3.3 Gate 8 (Integration sign-off)
    - AAP Section 0.7.3.5 Gate 10 (Test execution)
    - blitzy-odoo/addons/auth_v2/models/fnv_hash.py (module under test)
    - packages/admin-ui/src/flags/fnv-hash.ts (TypeScript counterpart)
    - packages/admin-ui/src/flags/__tests__/fnv-hash.spec.ts (TS test/generator)
"""

import json
import os

from odoo.tests import TransactionCase, tagged

from odoo.addons.auth_v2.models.fnv_hash import fnv1a32

# ---------------------------------------------------------------------------
# Module-Level Constants
# ---------------------------------------------------------------------------
#
# These constants are computed once at module import time so all test
# methods share the same fixture path and expected size. They are NOT
# exported (leading underscore) -- callers from outside this module
# MUST NOT depend on them. They are documentation-as-code: the
# fixture path traversal is explicit and auditable.

# Path to the cross-language parity fixture, relative to this test file.
# The fixture lives in the packages/admin-ui workspace (the canonical
# TypeScript-generated source of truth) and is consumed by BOTH the
# TypeScript suite (packages/admin-ui/src/flags/__tests__/fnv-hash.spec.ts)
# and this Python suite to verify Rule RF4 parity.
#
# Path computation (4 levels up from this file's directory to the
# repository root, then descending into packages/):
#
#   blitzy-odoo/addons/auth_v2/tests/test_feature_flags.py  <- this file
#   blitzy-odoo/addons/auth_v2/tests/                       <- dirname(__file__)
#   ../  -> blitzy-odoo/addons/auth_v2/
#   ../  -> blitzy-odoo/addons/
#   ../  -> blitzy-odoo/
#   ../  -> <repository root>
#   packages/admin-ui/src/flags/__tests__/fixtures/fnv-vectors.json
#
# ``os.path.normpath`` collapses the ``..`` references into a clean
# absolute path that is suitable for both ``open()`` and assertion
# error messages.
_FIXTURE_RELATIVE_PATH = os.path.normpath(
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        '..', '..', '..', '..',
        'packages', 'admin-ui', 'src', 'flags', '__tests__',
        'fixtures', 'fnv-vectors.json',
    ),
)

# Per AAP Section 0.5.1.2 the fixture contains EXACTLY 100 vectors.
# Composition (per the packages/admin-ui generator):
#   30 random emails (rollout 1-99) + 20 wildcards ('*') + 20 empty
#   subjects ('') + 10 rollout=0 + 10 rollout=100 + 10 rollout=50 = 100
_EXPECTED_VECTOR_COUNT = 100

# 32-bit unsigned upper bound. All hash outputs MUST fall in
# ``[0, _UINT32_MAX]`` regardless of input. This mirrors the
# ``& 0xFFFFFFFF`` mask in fnv_hash.py and the JavaScript ``>>> 0``
# unsigned-32 coercion in the TypeScript counterpart.
_UINT32_MAX = 0xFFFFFFFF


@tagged('post_install', '-at_install')
class TestFeatureFlagsFnvParity(TransactionCase):
    """Verifies Rule RF4: 32-bit FNV-1a output in Python is byte-identical
    to TypeScript for every (flag_name, subject) pair in the deterministic
    100-vector fixture committed by packages/admin-ui at::

        packages/admin-ui/src/flags/__tests__/fixtures/fnv-vectors.json

    The fixture is the cross-language ground truth: it is generated by the
    TypeScript implementation in
    ``packages/admin-ui/src/flags/__tests__/fnv-hash.spec.ts`` and loaded
    by both languages' test suites to assert determinism.

    This test exercises ONLY the pure ``fnv1a32`` function from
    ``odoo.addons.auth_v2.models.fnv_hash``. It does NOT exercise:

        - the HTTP client in ``auth_v2.py`` (Rule R13 fail-closed path)
        - the flag-evaluation cache in ``feature_flags.py`` (Rule RF3 fail-open)
        - any database tables (Rule R10 schema scope)
        - any environment variables (Rule R8 secrets containment)
        - the ``ir_http._authenticate`` override (Rules R3, R4)

    Per the AAP, this test is the literal Gate 8 / Gate 10 verification
    point for the Python side of the cross-language parity contract.

    The ``@tagged('post_install', '-at_install')`` decorator is the standard
    Odoo convention for tests that depend on installed addon code (the
    auth_v2 addon must be loaded for the relative import to resolve).
    The combination means:

        - ``'post_install'`` -- run the test AFTER addon installation
          completes, ensuring ``odoo.addons.auth_v2.models.fnv_hash`` is
          importable.
        - ``'-at_install'`` -- do NOT run during the install-time test
          pass (which runs before the registry is fully populated).

    ``TransactionCase`` provides automatic transaction rollback at
    test-end. Even though this test does not write to the database,
    ``TransactionCase`` is the most common Odoo test base and integrates
    cleanly with Odoo's test runner lifecycle.
    """

    def setUp(self):
        """Load the deterministic 100-vector parity fixture.

        The fixture path is computed at runtime from this file's location
        to ensure the test works whether invoked from the repo root, from
        inside the addon directory, or via Odoo's test runner.

        Three preconditions are asserted before the fixture is exposed
        to subsequent test methods:

            1. The fixture file MUST exist on disk. If absent (typically
               because the packages/admin-ui agent has not yet committed
               the file or the file was deleted), the test fails with a
               descriptive diagnostic identifying the expected path.

            2. The fixture MUST be valid JSON. ``ValueError`` (the parent
               class of ``json.JSONDecodeError`` in Python 3) is caught
               and converted to a ``self.fail()`` with the file path and
               the underlying parse error message.

            3. The fixture MUST contain exactly ``_EXPECTED_VECTOR_COUNT``
               (100) vectors. A mismatch indicates the canonical generator
               in packages/admin-ui has been altered without coordinating
               with the Python test suite.

        After ``setUp`` succeeds, ``self.vectors`` holds the parsed list
        of vector dicts and ``self._fixture_path`` holds the resolved
        absolute path (used in subsequent assertion error messages so
        diagnostics include the actual fixture location even when the
        suite is invoked from outside the repository root).

        Raises:
            AssertionError: If any precondition fails. The failure message
                is intentionally verbose so operators can quickly identify
                whether the fixture file or the parity contract is broken.
        """
        super().setUp()

        # Resolve the fixture path from this file's location. The path
        # is computed by ascending 4 levels (tests/ -> auth_v2/ -> addons/
        # -> blitzy-odoo/ -> repo root) then descending into packages/.
        fixture_path = _FIXTURE_RELATIVE_PATH

        # Defensive: the fixture file MUST exist. Per Rule RF4 the fixture
        # is the cross-language ground truth; its absence indicates a
        # broken pipeline (typically: the packages/admin-ui agent has not
        # yet committed the file or the file was deleted).
        self.assertTrue(
            os.path.isfile(fixture_path),
            msg=(
                "FNV-1a parity fixture not found at expected path. "
                "This file is the Rule RF4 cross-language parity ground "
                "truth and MUST exist for the Python parity test to run. "
                "Expected location: %s" % fixture_path
            ),
        )

        # Read and parse the fixture. UTF-8 is mandated for cross-platform
        # consistency; the fixture is ASCII-only in practice but the
        # encoding declaration matches the TypeScript producer's output.
        with open(fixture_path, encoding='utf-8') as f:
            try:
                self.vectors = json.load(f)
            except ValueError as exc:
                # ValueError is the parent class of json.JSONDecodeError
                # in Python 3; catching the parent maximizes compatibility
                # across stdlib and third-party JSON libraries.
                self.fail(
                    "FNV-1a parity fixture at %s is not valid JSON: %s"
                    % (fixture_path, exc),
                )

        # Per AAP Section 0.5.1.2: exactly 100 vectors. We use an
        # equality assertion (NOT >=) because the fixture composition
        # is fixed by the canonical generator and any deviation indicates
        # a coordination failure between the TypeScript producer and the
        # Python consumer.
        self.assertEqual(
            len(self.vectors),
            _EXPECTED_VECTOR_COUNT,
            msg=(
                "FNV-1a parity fixture has %d vectors but Rule RF4 / AAP "
                "Section 0.5.1.2 mandates exactly %d. The fixture composition "
                "MUST be 30 random emails + 20 wildcards + 20 empty subjects "
                "+ 10 rollout=0 + 10 rollout=100 + 10 rollout=50 = 100 vectors."
                % (len(self.vectors), _EXPECTED_VECTOR_COUNT)
            ),
        )

        # Save the absolute fixture path for diagnostic purposes if a
        # later assertion fails. Tests reference this in error messages
        # so failures include the actual on-disk fixture location.
        self._fixture_path = fixture_path

    def test_fixture_field_shape_and_ranges(self):
        """Verify each vector has the expected fields with valid types and ranges.

        This is a defensive pre-check to catch fixture corruption early,
        BEFORE the parity tests run. A failure here indicates the fixture
        file has been mutated outside the canonical generator and Rule RF4
        determinism is at risk.

        Each vector MUST have:

            - flag_name: str (any value, including empty string)
            - subject: str (any value, including '*' or '')
            - rollout_percentage: int in [0, 100]
            - expected_hash: int in [0, 0xFFFFFFFF]
            - expected_enabled: bool

        Per AAP Section 0.5.1.2, the field set in the fixture is stable:
        (flag_name, subject, rollout_percentage, expected_hash,
        expected_enabled). We do not assert field ORDER here (Python dicts
        preserve insertion order in 3.7+, but the Odoo runtime uses 3.10+,
        so this is fine); we only assert presence, types, and value
        ranges.

        The bool-vs-int distinction is critical: in Python ``bool`` is a
        subclass of ``int``, so ``isinstance(True, int)`` returns True.
        We use ``assertIsInstance(..., bool)`` for boolean fields to
        catch the mistake of storing ``1`` instead of ``True`` in the
        fixture, and ``assertNotIsInstance(..., bool)`` on integer fields
        to catch the inverse mistake.
        """
        for index, vector in enumerate(self.vectors):
            with self.subTest(vector_index=index):
                # Field presence -- detect missing keys with a clear
                # per-key diagnostic rather than a KeyError later.
                self.assertIn(
                    'flag_name', vector,
                    msg="vector[%d] missing 'flag_name'" % index,
                )
                self.assertIn(
                    'subject', vector,
                    msg="vector[%d] missing 'subject'" % index,
                )
                self.assertIn(
                    'rollout_percentage', vector,
                    msg="vector[%d] missing 'rollout_percentage'" % index,
                )
                self.assertIn(
                    'expected_hash', vector,
                    msg="vector[%d] missing 'expected_hash'" % index,
                )
                self.assertIn(
                    'expected_enabled', vector,
                    msg="vector[%d] missing 'expected_enabled'" % index,
                )

                # Type checks -- catch type-system mismatches between the
                # JSON producer (TypeScript) and consumer (Python) early.
                self.assertIsInstance(
                    vector['flag_name'], str,
                    msg="vector[%d].flag_name must be str (got %s)"
                    % (index, type(vector['flag_name']).__name__),
                )
                self.assertIsInstance(
                    vector['subject'], str,
                    msg="vector[%d].subject must be str (got %s)"
                    % (index, type(vector['subject']).__name__),
                )
                self.assertIsInstance(
                    vector['rollout_percentage'], int,
                    msg="vector[%d].rollout_percentage must be int (got %s)"
                    % (index, type(vector['rollout_percentage']).__name__),
                )
                # Note: bool is a subclass of int in Python; isinstance(True, int)
                # is True. We test bool FIRST to avoid the subclass trap.
                self.assertIsInstance(
                    vector['expected_enabled'], bool,
                    msg="vector[%d].expected_enabled must be bool (got %s)"
                    % (index, type(vector['expected_enabled']).__name__),
                )
                # rollout_percentage must be int and NOT bool (bool would
                # silently pass the isinstance check otherwise).
                self.assertNotIsInstance(
                    vector['rollout_percentage'], bool,
                    msg="vector[%d].rollout_percentage must be int, not bool"
                    % index,
                )
                # expected_hash must be int but NOT bool (bool would silently
                # pass the isinstance check otherwise).
                self.assertIsInstance(
                    vector['expected_hash'], int,
                    msg="vector[%d].expected_hash must be int (got %s)"
                    % (index, type(vector['expected_hash']).__name__),
                )
                self.assertNotIsInstance(
                    vector['expected_hash'], bool,
                    msg="vector[%d].expected_hash must be int, not bool"
                    % index,
                )

                # Range checks -- enforce the documented value spaces.
                self.assertGreaterEqual(
                    vector['rollout_percentage'], 0,
                    msg="vector[%d].rollout_percentage must be >= 0 (got %d)"
                    % (index, vector['rollout_percentage']),
                )
                self.assertLessEqual(
                    vector['rollout_percentage'], 100,
                    msg="vector[%d].rollout_percentage must be <= 100 (got %d)"
                    % (index, vector['rollout_percentage']),
                )
                self.assertGreaterEqual(
                    vector['expected_hash'], 0,
                    msg="vector[%d].expected_hash must be >= 0 (got %d)"
                    % (index, vector['expected_hash']),
                )
                self.assertLessEqual(
                    vector['expected_hash'], _UINT32_MAX,
                    msg=(
                        "vector[%d].expected_hash must be <= 0x%08x "
                        "(uint32 max; got %d)"
                        % (index, _UINT32_MAX, vector['expected_hash'])
                    ),
                )

    def test_fnv1a32_byte_parity(self):
        """Assert that Python fnv1a32 produces byte-identical 32-bit hashes
        for every vector in the fixture (Rule RF4).

        This is THE Rule RF4 verification gate. For each of the 100 vectors,
        we compute the Python hash and compare it byte-for-byte against the
        fixture's pre-computed expected_hash (which was generated by the
        TypeScript canonical implementation in
        ``packages/admin-ui/src/flags/fnv-hash.ts``).

        Failure mode interpretation:

            - If 1+ vectors fail with consistent off-by patterns:
              Likely a sign-extension / unsigned-32 boundary bug in
              fnv_hash.py (e.g., missing ``& 0xFFFFFFFF`` after
              multiplication).

            - If 1+ vectors fail with completely different values:
              Likely an algorithm error (e.g., FNV-1 vs FNV-1a confusion,
              wrong prime, wrong offset basis, or wrong UTF-8 encoding).

            - If only vectors with non-ASCII subjects fail:
              Likely a UTF-8 encoding mismatch (e.g., using 'utf-16' or
              str.encode() with the wrong codec).

            - If only vectors with empty subjects fail:
              Likely the separator ':' is not being applied for empty
              input.

        Per Rule RF4, ALL 100 vectors MUST pass. There are no acceptable
        deviations.

        Each iteration is wrapped in ``self.subTest(...)`` so all 100
        vectors run even if one fails; this surfaces the FULL set of
        failures rather than aborting at the first mismatch. Critical
        for diagnosing algorithm bugs that affect a subset of inputs
        (e.g., only multi-byte UTF-8 or only empty subjects).
        """
        for index, vector in enumerate(self.vectors):
            flag_name = vector['flag_name']
            subject = vector['subject']
            expected_hash = vector['expected_hash']

            # Compute the Python hash. The signature is fnv1a32(flag_name,
            # subject) -- the function internally concatenates with ':'
            # and encodes UTF-8 before iterating bytes.
            actual_hash = fnv1a32(flag_name, subject)

            with self.subTest(
                vector_index=index,
                flag_name=flag_name,
                subject=subject,
                rollout_percentage=vector['rollout_percentage'],
            ):
                self.assertEqual(
                    actual_hash,
                    expected_hash,
                    msg=(
                        "FNV-1a parity FAILURE at vector[%d]:\n"
                        "  flag_name = %r\n"
                        "  subject   = %r\n"
                        "  rollout_%% = %d\n"
                        "  expected_hash (TypeScript) = %d (0x%08x)\n"
                        "  actual_hash   (Python)     = %d (0x%08x)\n"
                        "  delta = %d\n"
                        "Rule RF4 (FNV-1a determinism) is violated. The Python "
                        "fnv1a32 implementation in odoo.addons.auth_v2.models."
                        "fnv_hash MUST produce byte-identical output to the "
                        "TypeScript canonical implementation in "
                        "packages/admin-ui/src/flags/fnv-hash.ts. "
                        "Verify the constants (offset basis 0x811c9dc5, prime "
                        "0x01000193, mask 0xFFFFFFFF), the algorithm order "
                        "(XOR-then-multiply for FNV-1a, NOT multiply-then-XOR "
                        "for FNV-1), the separator (':'), and the UTF-8 "
                        "encoding."
                        % (
                            index, flag_name, subject,
                            vector['rollout_percentage'],
                            expected_hash, expected_hash,
                            actual_hash, actual_hash,
                            actual_hash - expected_hash,
                        )
                    ),
                )

    def test_rollout_evaluation_parity(self):
        """Assert the full rollout evaluation produces byte-identical booleans
        for every vector (Rule RF4 + 4-step order).

        For each vector, we compute::

            python_enabled = (fnv1a32(flag_name, subject) % 100) < rollout_percentage

        and compare to the fixture's expected_enabled. This verifies the
        canonical 4-step evaluation order's hash-bucket step (step 4)
        produces identical decisions across both languages.

        Note: Steps 1-3 of the 4-step order (subject override, '*' override,
        ``enabled=false`` short-circuit) are evaluated by the API server
        (packages/admin-ui) and reflected in the fixture's setup; this
        test only verifies step 4 (the FNV bucket comparison). Per AAP
        Section 0.7.2 RF4, step 4 is where the cross-language parity is
        most fragile and most important.

        The test exercises the boundary cases via the fixture composition:

            - rollout_percentage=0:   NEVER enabled (all 10 vectors must
              be False because bucket is in [0, 99] and 0 < 0 is False)
            - rollout_percentage=100: ALWAYS enabled (all 10 vectors must
              be True because bucket < 100 is always True)
            - rollout_percentage=50:  half enabled (depends on hash bucket)
            - rollout_percentage=1-99: continuous spectrum

        Failure mode interpretation:

            - If only rollout=0 vectors fail (returning True): the
              comparison uses '<=' instead of '<' (off-by-one).
            - If only rollout=100 vectors fail (returning False): the
              comparison uses '<' instead of '<=' on a 0-based bucket
              -- impossible in our spec since bucket is in [0, 99] so
              bucket < 100 is always True; this would indicate a
              type-coercion bug.
            - If random vectors fail: indicates the upstream byte_parity
              test is also failing -- fix that test first since this
              test depends on byte parity.
        """
        for index, vector in enumerate(self.vectors):
            flag_name = vector['flag_name']
            subject = vector['subject']
            rollout_percentage = vector['rollout_percentage']
            expected_enabled = vector['expected_enabled']

            # Compute the bucket (0-99) and the rollout decision.
            # The comparison MUST be strict less-than ('<'), NOT '<='.
            # With rollout=0, bucket (in [0, 99]) is never < 0, so the
            # result is False for all subjects (matches the fixture).
            # With rollout=100, bucket < 100 is always True (matches).
            actual_hash = fnv1a32(flag_name, subject)
            bucket = actual_hash % 100
            actual_enabled = bucket < rollout_percentage

            with self.subTest(
                vector_index=index,
                flag_name=flag_name,
                subject=subject,
                rollout_percentage=rollout_percentage,
            ):
                self.assertEqual(
                    actual_enabled,
                    expected_enabled,
                    msg=(
                        "Rollout evaluation parity FAILURE at vector[%d]:\n"
                        "  flag_name          = %r\n"
                        "  subject            = %r\n"
                        "  rollout_percentage = %d\n"
                        "  hash    (Python)   = %d (0x%08x)\n"
                        "  bucket  (hash %% 100) = %d\n"
                        "  expected_enabled (TypeScript) = %s\n"
                        "  actual_enabled   (Python)     = %s\n"
                        "Rule RF4 (rollout determinism) is violated. The "
                        "comparison must be `bucket < rollout_percentage` "
                        "(strict less-than). If this test fails but "
                        "test_fnv1a32_byte_parity passes, the bug is in the "
                        "rollout-comparison operator (this test) or the "
                        "consumer (feature_flags.py / checkFlag.ts). If both "
                        "fail, the bug is in the FNV-1a implementation."
                        % (
                            index, flag_name, subject, rollout_percentage,
                            actual_hash, actual_hash,
                            bucket,
                            expected_enabled, actual_enabled,
                        )
                    ),
                )

    def test_fnv1a32_default_subject_argument(self):
        """Verify ``fnv1a32(name) == fnv1a32(name, '')`` -- the default
        subject argument behaves as documented.

        Per the fnv_hash.py contract, ``subject`` defaults to ``''``
        (empty string). This test verifies that callers omitting the
        subject get the same result as passing the empty string explicitly.
        This matches the TypeScript pattern
        ``flagName + ':' + (subject ?? '')`` where ``undefined`` and ``''``
        are equivalent under the JavaScript ``??`` (nullish-coalescing)
        operator.

        Critical for: ``feature_flags.is_enabled('AUTH_V2_ENABLED')``
        (the most common Odoo call site, with no subject -- the global
        evaluation of the kill-switch flag).

        This test guards against regression where someone changes the
        default to ``None`` (which would raise ``TypeError`` on the
        ``+`` concatenation) or to a non-empty sentinel like ``'<global>'``
        (which would silently break parity by hashing different bytes).
        """
        # Pick a few representative names: the canonical addon flag, an
        # empty flag_name (degenerate but defined), a single-char name,
        # and a multi-word name. Together these exercise short, empty,
        # and long inputs without loading the fixture.
        sample_names = [
            'AUTH_V2_ENABLED',  # the canonical addon flag
            '',                 # empty flag_name (degenerate but defined)
            'A',                # single-char
            'feature_with_long_underscore_name',  # multi-word
        ]
        for name in sample_names:
            with self.subTest(flag_name=name):
                hash_with_default = fnv1a32(name)
                hash_with_explicit_empty = fnv1a32(name, '')
                self.assertEqual(
                    hash_with_default,
                    hash_with_explicit_empty,
                    msg=(
                        "fnv1a32(%r) and fnv1a32(%r, '') produced different "
                        "hashes (%d vs %d). The subject default argument "
                        "must be '' (empty string) per the cross-language "
                        "parity contract."
                        % (
                            name, name,
                            hash_with_default, hash_with_explicit_empty,
                        )
                    ),
                )

    def test_fnv1a32_returns_uint32_range(self):
        """Verify ``fnv1a32`` always returns an integer in ``[0, 0xFFFFFFFF]``.

        This is a defensive test against accidental sign-extension and
        overflow bugs. Python's ``int`` is unbounded, so without explicit
        masking (``& 0xFFFFFFFF``), an FNV-1a multiplication would silently
        overflow the 32-bit window and produce values >= 2**32. This test
        asserts that the documented mask is applied correctly.

        We test the boundary inputs from the fixture (first 10 vectors,
        for breadth without redundancy) plus a few ad-hoc cases that
        stress the implementation: long inputs that maximize the number
        of mask applications, control bytes (0x00-0x03), and multi-byte
        UTF-8 characters (e.g., 'caf\u00e9' which encodes to 5 bytes
        rather than 4 because of the e-acute character).

        ``assertNotIsInstance(h, bool)`` guards against the inverse
        bool-as-int trap: if the function ever returned ``True`` or
        ``False`` (which would coerce to 1 or 0 in arithmetic contexts),
        this assertion would catch it.
        """
        # Sample from the fixture (first 10 vectors) for breadth without
        # repeating the work of test_fnv1a32_byte_parity.
        for index, vector in enumerate(self.vectors[:10]):
            with self.subTest(source='fixture', index=index):
                h = fnv1a32(vector['flag_name'], vector['subject'])
                self.assertGreaterEqual(
                    h, 0,
                    msg="fnv1a32 returned negative value: %d" % h,
                )
                self.assertLessEqual(
                    h, _UINT32_MAX,
                    msg=(
                        "fnv1a32 returned value > 0xFFFFFFFF: %d (0x%x). "
                        "The 32-bit mask is missing or applied at the wrong "
                        "step. Verify fnv_hash.py applies `& 0xFFFFFFFF` "
                        "AFTER each multiplication." % (h, h)
                    ),
                )
                self.assertIsInstance(
                    h, int,
                    msg="fnv1a32 must return int, got %s"
                    % type(h).__name__,
                )
                self.assertNotIsInstance(
                    h, bool,
                    msg="fnv1a32 must return int, not bool",
                )

        # Ad-hoc cases for breadth: stress the mask and UTF-8 paths
        # with long inputs and non-ASCII characters that are NOT in the
        # canonical fixture.
        ad_hoc_inputs = [
            ('', ''),                                   # both empty -> hash of ':'
            ('a' * 1000, ''),                           # long flag_name
            ('flag', 'b' * 1000),                       # long subject
            ('a' * 100, 'b' * 100),                     # both long
            ('flag', '\x00\x01\x02\x03'),               # control bytes
            ('flag', 'caf\u00e9'),                      # non-ASCII (multi-byte UTF-8)
        ]
        for flag_name, subject in ad_hoc_inputs:
            with self.subTest(
                source='ad_hoc',
                flag_name=flag_name[:20],
                subject=subject[:20],
            ):
                h = fnv1a32(flag_name, subject)
                self.assertGreaterEqual(
                    h, 0,
                    msg="fnv1a32 returned negative value: %d" % h,
                )
                self.assertLessEqual(
                    h, _UINT32_MAX,
                    msg=(
                        "fnv1a32 returned value > 0xFFFFFFFF: %d (0x%x)"
                        % (h, h)
                    ),
                )
                self.assertIsInstance(
                    h, int,
                    msg="fnv1a32 must return int, got %s"
                    % type(h).__name__,
                )
                self.assertNotIsInstance(
                    h, bool,
                    msg="fnv1a32 must return int, not bool",
                )
