# Copyright 2024 Enterprise Accounting Team
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

"""Deferred revenue recognition line (``account.deferred.line``).

Single recognition entry belonging to an ``account.deferred.schedule``.
Each line carries the calendar date, the amount to recognize on that date, the
currency/company/partner inherited from the parent schedule (stored-related for
efficient aggregation), and the posting state (``draft`` or ``posted``).

The DR-003 cut-off wizard transitions a line from ``draft`` to ``posted`` and
populates ``move_id`` / ``move_line_ids`` with the journal entry and its
individual debit/credit lines.  The bidirectional relationship from this line
to the generated ``account.move`` enables full audit trail from the recognition
plan to the journal entries.

This is a **net-new model** per AAP rule R-03 (``_name`` only — no ``_inherit``
on a pre-existing model).  R-05 does not apply to this file because it does not
extend any core model directly; it only references ``account.move`` and
``account.move.line`` via relational fields.
"""

from calendar import monthrange

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError


class AccountDeferredLine(models.Model):
    """Single recognition entry within a deferred revenue schedule.

    Each line represents one period's recognition (e.g., January 2024 = $1,000).
    Lines are auto-generated by
    ``account.deferred.schedule._compute_recognition_schedule`` from the
    schedule's ``start_date``, ``end_date``, ``total_amount``, and
    ``recognition_method`` (DR-002 automatic period allocation).

    The DR-003 cut-off wizard transitions ``state`` from ``draft`` to
    ``posted`` and populates ``move_id`` / ``move_line_ids`` with the generated
    journal entries.  Two bidirectional invariants are enforced:

    * ``state == 'posted'`` implies ``move_id`` is set.
    * ``state == 'draft'`` implies ``move_id`` is **not** set.

    Net-new model per AAP rule R-03 (``_name`` only, no ``_inherit`` on an
    existing model).
    """

    _name = 'account.deferred.line'
    _description = 'Deferred Revenue Recognition Line'
    # Chronological primary ordering; sequence resolves ties within the same
    # recognition_date; id is the final tiebreaker for deterministic ordering.
    _order = 'recognition_date, sequence, id'
    # Odoo 19.0 declarative multi-company safety.  Combined with check_company
    # on every Many2one below, this ensures every record is scoped to a company
    # the current user has access to.
    _check_company_auto = True

    # ------------------------------------------------------------------
    # Relational fields — parent link and ordering
    # ------------------------------------------------------------------
    schedule_id = fields.Many2one(
        comodel_name='account.deferred.schedule',
        string='Schedule',
        required=True,
        ondelete='cascade',
        index=True,
        check_company=True,
        help=(
            "Parent deferred revenue schedule this recognition line belongs "
            "to.  ``ondelete='cascade'`` ensures that deleting a draft "
            "schedule also removes its recognition plan; posted schedules are "
            "protected by the ``_check_posted_has_move`` constraint plus the "
            "schedule's own state guards."
        ),
    )

    sequence = fields.Integer(
        string='Sequence',
        default=10,
        help=(
            "Display order for lines sharing the same ``recognition_date``.  "
            "Default 10 matches the Odoo convention that leaves gaps between "
            "explicit user-provided sequence values."
        ),
    )

    # ------------------------------------------------------------------
    # Period + amount fields — the recognition plan
    # ------------------------------------------------------------------
    recognition_date = fields.Date(
        string='Recognition Date',
        required=True,
        help=(
            "Calendar date on which this portion of the deferred amount is "
            "recognized into the P&L account.  Typically the last day of each "
            "month for monthly straight-line schedules, or calendar-day "
            "prorated for date-based schedules (DR-002 Scenario 2)."
        ),
    )

    recognition_amount = fields.Monetary(
        string='Recognition Amount',
        required=True,
        currency_field='currency_id',
        help=(
            "Amount to recognize in schedule currency on the "
            "``recognition_date``.  For straight-line method, all amounts are "
            "equal with the rounding adjustment on the last line.  For "
            "date-based, the amount is prorated by calendar days in the "
            "period (DR-002 Scenario 2)."
        ),
    )

    # ------------------------------------------------------------------
    # Related / denormalized fields — inherited from parent schedule
    # ------------------------------------------------------------------
    # These stored-related fields denormalize schedule-level metadata onto the
    # line for efficient filtering and aggregation in the DR-004 recognition
    # dashboard and in reports.  ``readonly=True`` prevents accidental
    # double-writes; the authoritative value always lives on the schedule.
    currency_id = fields.Many2one(
        related='schedule_id.currency_id',
        store=True,
        readonly=True,
        help=(
            "Currency of the recognition amount, inherited from parent "
            "schedule (denormalized for performance)."
        ),
    )

    company_id = fields.Many2one(
        related='schedule_id.company_id',
        store=True,
        readonly=True,
        help=(
            "Company owning this line, inherited from parent schedule "
            "(denormalized for performance; used for multi-company record "
            "rule enforcement)."
        ),
    )

    partner_id = fields.Many2one(
        related='schedule_id.partner_id',
        store=True,
        readonly=True,
        string='Partner',
        help=(
            "Partner associated with the parent schedule.  Useful for "
            "grouping in the DR-004 recognition dashboard and in reports."
        ),
    )

    # ------------------------------------------------------------------
    # State + posting fields — DR-003 cut-off wizard populates these
    # ------------------------------------------------------------------
    state = fields.Selection(
        selection=[
            ('draft', 'Pending'),
            ('posted', 'Posted'),
        ],
        string='Status',
        default='draft',
        required=True,
        copy=False,
        index=True,
        help=(
            "**draft** — the line is scheduled but no journal entry has been "
            "posted yet.\n"
            "**posted** — the DR-003 cut-off wizard has created ``move_id`` "
            "and the recognition has been recorded in the P&L."
        ),
    )

    move_id = fields.Many2one(
        comodel_name='account.move',
        string='Journal Entry',
        readonly=True,
        copy=False,
        ondelete='restrict',
        check_company=True,
        index=True,
        help=(
            "Journal entry created by the DR-003 cut-off wizard when this "
            "line was posted.  ``ondelete='restrict'`` at the database level "
            "prevents accidental deletion of the entry while a recognition "
            "line still references it — use the schedule's reversal action "
            "instead."
        ),
    )

    # The explicit relation/column names prevent Odoo's auto-generated name
    # from colliding with another module's m2m between the same two models in
    # a shared-database deployment.  Pattern matches the Odoo core convention
    # of explicitly naming relation tables whenever the default would be
    # ambiguous or excessively long.
    move_line_ids = fields.Many2many(
        comodel_name='account.move.line',
        relation='account_deferred_line_move_line_rel',
        column1='deferred_line_id',
        column2='move_line_id',
        string='Journal Lines',
        readonly=True,
        copy=False,
        help=(
            "Individual debit and credit journal lines generated for this "
            "recognition.  Typically two lines (one debit to the deferred "
            "account, one credit to the recognition account), but may be "
            "more when analytic distribution splits apply."
        ),
    )

    # ------------------------------------------------------------------
    # Computed audit-trail field
    # ------------------------------------------------------------------
    days_in_period = fields.Integer(
        string='Days in Period',
        compute='_compute_days_in_period',
        store=True,
        help=(
            "Calendar days in the month containing ``recognition_date``.  "
            "Used as the audit-trail denominator for date-based recognition "
            "(DR-002 Scenario 2 prorated allocation), making the proration "
            "basis visible to auditors."
        ),
    )

    # ==================================================================
    # Compute methods
    # ==================================================================
    @api.depends('recognition_date')
    def _compute_days_in_period(self):
        """Derive ``days_in_period`` from the month containing recognition_date.

        Uses :func:`calendar.monthrange` (standard library) to return the
        number of calendar days in the month.  When ``recognition_date`` is
        unset (e.g., a freshly created unsaved line in the form view), the
        value falls back to ``0`` to keep the field safe for storage.

        The import of :func:`calendar.monthrange` lives at the module level
        to satisfy ``PLC0415`` (imports-outside-top-level); this computation
        is the only place in the file that requires it, and the call cost is
        negligible.
        """
        for line in self:
            if not line.recognition_date:
                line.days_in_period = 0
                continue
            # monthrange(year, month) -> (first_weekday_of_month, days_in_month)
            # We discard the weekday and keep only the day count.
            _first_weekday, days_in_month = monthrange(
                line.recognition_date.year,
                line.recognition_date.month,
            )
            line.days_in_period = days_in_month

    # ==================================================================
    # Constraints — data-integrity invariants
    # ==================================================================
    @api.constrains('state', 'move_id')
    def _check_posted_has_move(self):
        """Enforce the bidirectional ``state``/``move_id`` invariant.

        A line may only be in state ``posted`` when a journal entry is linked,
        and only in state ``draft`` when no journal entry is linked.  Any
        other combination indicates either a failed posting or a manual
        tampering attempt; both are rejected with a clear, actionable error.
        """
        for line in self:
            if line.state == 'posted' and not line.move_id:
                raise ValidationError(_(
                    "Deferred recognition line cannot be marked as posted "
                    "without a linked journal entry.  Use the cut-off wizard "
                    "to post the schedule (DR-003).",
                ))
            if line.state == 'draft' and line.move_id:
                raise ValidationError(_(
                    "Deferred recognition line has a linked journal entry "
                    "but is still marked draft.  This indicates a data "
                    "integrity issue — run the schedule's state "
                    "recalculation or contact support.",
                ))

    @api.constrains('recognition_amount')
    def _check_recognition_amount(self):
        """Reject negative recognition amounts.

        Zero is permitted for intentional skip lines (e.g., a calendar month
        with no active days in a date-based schedule).  Negative recognitions
        are never allowed — reversal is handled at the ``account.move`` level
        via the DR-003 cut-off wizard's reversal mode, not by negative
        amounts on recognition lines.
        """
        for line in self:
            if line.recognition_amount < 0:
                raise ValidationError(_(
                    "Recognition amount must be non-negative (got "
                    "%(amount)s on %(date)s).  Negative recognitions are "
                    "not supported; use a reversal entry via the cut-off "
                    "wizard instead.",
                    amount=line.recognition_amount,
                    date=line.recognition_date,
                ))

    # ==================================================================
    # User-facing actions
    # ==================================================================
    def action_view_move(self):
        """Open the linked journal entry in its standard form view.

        Invoked from the tree/form view button on the line record.  Returns
        the standard Odoo ``ir.actions.act_window`` dictionary for viewing a
        single ``account.move`` record.  Raises ``ValidationError`` when no
        journal entry is yet linked (i.e., the line has not been posted via
        the DR-003 cut-off wizard).
        """
        self.ensure_one()
        if not self.move_id:
            raise ValidationError(_(
                "No journal entry is linked to this recognition line yet.  "
                "Post the schedule via the cut-off wizard (DR-003) first.",
            ))
        return {
            'type': 'ir.actions.act_window',
            'name': _('Journal Entry'),
            'res_model': 'account.move',
            'res_id': self.move_id.id,
            'view_mode': 'form',
            'target': 'current',
        }
